-- lp_platform: 平台共享数据库，存储租户元数据
CREATE DATABASE IF NOT EXISTS lp_platform DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE lp_platform;

CREATE TABLE IF NOT EXISTS tenants (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL COMMENT '商户名称',
  db_name VARCHAR(64) NOT NULL UNIQUE COMMENT '商户独立数据库名',
  phone VARCHAR(20) NOT NULL UNIQUE COMMENT '注册手机号',
  status TINYINT NOT NULL DEFAULT 1 COMMENT '1=正常 0=停用',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;
